### ISSUE TITLE
Build Dockerfile - 2

### ISSUE THREAD

**Issue by waddle77** [uvdl/yocto-ornl#18]
The first choice for building the Yocto build system would be using Docker.  A Dockerfile needs to be created that allows a choice of what build is being created.  

**Acceptance Criteria** 
1. Dockerfile preps a new machine that has all the necessary dependencies for building.
1. During the prep the Dockerfile needs to be able to clone the correct layers for the build.

**Comment by bvacaliuc** [comment]
Using Docker on Windows, I setup a branch work on this feature because I found myself in a position to need it.  The branch is [feature/docker-again](https://github.com/uvdl/yocto-ornl/tree/feature/docker-again).  My steps:

```
PS> docker build -t yocto-ornl:core .
PS> docker run -p 8000:8000 -v full-path-to-current-dir:/opt -it yocto-ornl:core
```
And then, in the docker interactive:
```
build@5bb543b241db:~/yocto-ornl$ make toaster
build@5bb543b241db:~/yocto-ornl$ make environment
build@5bb543b241db:~/yocto-ornl$ cd /home/build/ornl-dart-yocto && MACHINE=var-som-mx6-ornl DISTRO=fslc-framebuffer EULA=1        . setup-environment build_ornl
build@5bb543b241db:~/ornl-dart-yocto/build_ornl$ source toaster start webport=0.0.0.0:8000
build@5bb543b241db:~/ornl-dart-yocto/build_ornl$ export LANG=en_US.UTF-8
build@5bb543b241db:~/ornl-dart-yocto/build_ornl$ bitbake var-dev-update-full-image
```
Which eventually fails with this error:
[log.do_overwrite_defconfig.19157.txt](https://github.com/uvdl/yocto-ornl/files/5514275/log.do_overwrite_defconfig.19157.txt)

If you look at the missing path, it seems incomplete; like the kernel has not been cloned from the upstream repos:
```
build@5bb543b241db:~/ornl-dart-yocto/build_ornl$ ls tmp/work/var_som_mx6_ornl-fslc-linux-gnueabi/linux-variscite/4.9.88-r0
recipe-sysroot  recipe-sysroot-native  temp
```
